version: '3.7'

services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    ports:
      - '18079:8000'
    expose:
      - 8000
    command: ['-jar', 'DynamoDBLocal.jar', '-sharedDb', '-inMemory']

  dynamoInit:
    depends_on:
      - dynamodb-local
    image: banst/awscli
    environment:
      TABLE_MOVIES: thepixardb_movies
      AWS_PROFILE: default
    volumes:
      - ~/.aws/:/root/.aws:ro
    command: dynamodb create-table --endpoint-url http://dynamodb-local:8000 --billing-mode PAY_PER_REQUEST --region sa-east-1 --table-name thepixardb_movies --attribute-definitions AttributeName=pk,AttributeType=S AttributeName=sk,AttributeType=S --key-schema AttributeName=pk,KeyType=HASH AttributeName=sk,KeyType=RANGE

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - '8001:8001'
    environment:
      DYNAMO_ENDPOINT: http://dynamodb-local:8000
      TABLE_MOVIES: thepixardb_movies
      AWS_PROFILE: default
      AWS_REGION: sa-east-1
    volumes:
      - ~/.aws/:/root/.aws:ro
    depends_on:
      - dynamodb-local

  database:
    image: thepixardb/database
    build:
      context: .
      target: database
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      DYNAMO_ENDPOINT: http://dynamodb-local:8000
      TABLE_MOVIES: thepixardb_movies
      AWS_PROFILE: default
      AWS_REGION: sa-east-1
    volumes:
      - ~/.aws/:/root/.aws:ro
    depends_on:
      dynamoInit:
        condition: service_started
    ports:
      - '3000:3000'
    command: yarn dev

  api:
    image: thepixardb/api
    build:
      context: .
      target: api
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    environment:
      HTTP_PORT: 8080
      HTTP_ADDRESS: 0.0.0.0
      DYNAMO_ENDPOINT: http://dynamodb-local:8000
      TABLE_MOVIES: thepixardb_movies
      AWS_PROFILE: default
      AWS_REGION: sa-east-1
    ports:
      - '8080:8080'
    volumes:
      - .:/usr/src/app
      - ~/.aws/:/root/.aws:ro
    depends_on:
      database:
        condition: service_started
      dynamoInit:
        condition: service_started
    command: yarn dev
