version: '3.7'

services:
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb-local
    ports:
      - '8000:8000'

  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    ports:
      - '8001:8001'
    environment:
      DYNAMO_ENDPOINT: 'http://dynamodb-local:8000'
      AWS_REGION: 'us-west-1'
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: local
    depends_on:
      - dynamodb-local

  database:
    image: thepixardb/database
    build:
      context: .
      target: database
      dockerfile: Dockerfile
    ports:
      - '3002:3002'
    environment:
      DYNAMO_ENDPOINT: 'http://dynamodb-local:8000'
      AWS_REGION: 'us-west-1'
      AWS_ACCESS_KEY_ID: local
      AWS_SECRET_ACCESS_KEY: local
    depends_on:
      - dynamodb-local

  api:
    image: thepixardb/api
    build:
      context: .
      target: api
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    environment:
      - HTTP_PORT=3000
      - HTTP_ADDRESS=0.0.0.0
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - ~/.aws/:/root/.aws:ro
    command: yarn dev
