name: Pull Request

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  app-build:
    name: App Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Yarn Install
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - name: Yarn Build
        id: yarnbuild
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build
      - name: Copy node_modules
        run: sudo cp -rf node_modules dist/
      - name: Save Cache
        id: app-build
        uses: actions/cache@v2
        with:
          path: ./*
          key: ${{ github.sha }}
  terraform-fmt:
    name: Terraform fmt
    needs: app-build
    runs-on: ubuntu-latest
    steps:
      - name: Get Cache
        id: app-build
        uses: actions/cache@v2
        with:
          path: ./*
          key: ${{ github.sha }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform Init
        id: init
        working-directory: ./infra
        run: terraform init -backend=true
      - name: Terraform Format
        id: fmt
        working-directory: ./infra
        run: terraform fmt -check
  terraform-validate:
    name: Terraform Validate
    needs: app-build
    runs-on: ubuntu-latest
    steps:
      - name: Get Cache
        id: app-build
        uses: actions/cache@v2
        with:
          path: ./*
          key: ${{ github.sha }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform Init
        id: init
        working-directory: ./infra
        run: terraform init -backend=true
      - name: Terraform Validate
        id: validate
        working-directory: ./infra
        run: terraform validate -no-color
  terraform-plan:
    name: Terraform plan
    needs: app-build
    runs-on: ubuntu-latest
    steps:
      - name: Get Cache
        id: app-build
        uses: actions/cache@v2
        with:
          path: ./*
          key: ${{ github.sha }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Terraform Init
        id: init
        working-directory: ./infra
        run: terraform init -backend=true
      - name: Terraform Plan
        id: plan
        working-directory: ./infra
        run: terraform plan -no-color
