name: Terraform Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  deploy:
    name: 'Deploy'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Yarn Install
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install
      - name: Yarn Build
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: build
      - name: Copy node_modules to package
        run: sudo cp -rf node_modules build/
      - name: Show folder files
        run: ls -la
      - name: Terraform fmt
        id: fmt
        working-directory: ./infra
        run: terraform fmt -check
      - name: Terraform Init
        id: init
        working-directory: ./infra
        run: terraform init -backend=true
      - name: Terraform Validate
        id: validate
        working-directory: ./infra
        run: terraform validate -no-color
      - name: Terraform Deploy
        id: deploy
        working-directory: ./infra
        run: terraform apply -auto-approve
  tag:
    needs: deploy
    name: 'Create new tag'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure committer
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
      - name: Bump version
        run: npx standard-version
      - name: Push tag
        run: git push --follow-tags origin main
